Add basic typing to the methods in logger
nautobot/nornir-nautobot pull request #66
Opened 2022-10-11 06:50 UTC by KalleDK

Added basic typing info, such that people who develops with typing doesn't get error in those lines.

2022-11-15 21:12 UTC, whitej6 commented
@KalleDK can you run `invoke tests` locally and resolve and failing tests. The current failing test is from additional whitespace in `bool = False`

Also can you reach out to me via jeremy.white@networktocode.com This PR was considered part of hacktoberfest and would like to show our appreciation for your first time contribution.

2022-11-16 01:15 UTC, KalleDK commented
> @KalleDK can you run `invoke tests` locally and resolve and failing tests. The current failing test is from additional whitespace in `bool = False`
> 
> Also can you reach out to me via [jeremy.white@networktocode.com](mailto:jeremy.white@networktocode.com) This PR was considered part of hacktoberfest and would like to show our appreciation for your first time contribution.

Done!

2022-11-17 00:19 UTC, jvanderaa requested changes
This should remain required, not optional.

2022-11-17 00:19 UTC, jvanderaa commented on nornir_nautobot/utils/logger.py
> +    def __init__(self, name: Optional[str], nautobot_job=None, debug: bool = False, job_result=None):
```suggestion
    def __init__(self, name: str, nautobot_job=None, debug: bool = False, job_result=None):
```

2022-11-17 00:42 UTC, KalleDK commented on nornir_nautobot/utils/logger.py
> +    def __init__(self, name: Optional[str], nautobot_job=None, debug: bool = False, job_result=None):
Fixing asap

2022-11-17 01:11 UTC, jvanderaa approved these changes

2022-11-17 01:27 UTC, merged